CREATE TABLE WEATHERLOG(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  RESPONSEID VARCHAR (50) NOT NULL,
  LOCATION  VARCHAR (50) NOT NULL,
  ACTUALWEATHER VARCHAR (50) NOT NULL,
  TEMPERATURE VARCHAR (50) NOT NULL,
  DTIMEINSERTED TIMESTAMP
);